#!/bin/bash

if [[ -z "$DESTINATIONS" ]]; then
    echo "DESTINATIONS is required in the format of either <destip>:<destport>:<localport> or <destip>:<destport> (localport will default to destport for the 2nd format)"
    exit 1
fi

echo "# This file is auto-generated by $0 upon container startup based on environment variable DESTINATIONS" > /etc/rinetd.conf

if [[ -n "$LOGFILE" ]]; then
    echo "logfile $LOGFILE" >> /etc/rinetd.conf
    if [[ -n "$LOGCOMMON" ]]; then
        echo "logcommon" >> /etc/rinetd.conf
    fi
fi

ISVALID=0
readarray -d ' ' -t DESTINATIONS_ARR < <(printf '%s' "$DESTINATIONS")
for DEST in "${DESTINATIONS_ARR[@]}"
do
    readarray -d ':' -t DESTARR < <(printf '%s' "$DEST")
    if [[ ${#DESTARR[@]} -lt 2 ]]; then
        echo "Ignoring destination '$DEST' as it is in invalid format. Must be either <destip>:<destport>:<localport> or <destip>:<destport>"
    else
    	DSTIP=${DESTARR[0]}
    	DSTPORT=${DESTARR[1]}
        if [[ ${#DESTARR[@]} -gt 2 ]]; then
            LOCPORT=${DESTARR[2]}
        else
            LOCPORT=${DSTPORT}
        fi
        echo "0.0.0.0 $LOCPORT $DSTIP $DSTPORT" >> /etc/rinetd.conf
	ISVALID=1
    fi 
done

if [[ $ISVALID -eq 0 ]]; then
    echo "Error! No valid destination found in DESTINATIONS variable."
    exit 1
fi

/usr/sbin/rinetd -f -c /etc/rinetd.conf
